// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK3-ZDjJ5kFiyap-Or-JIzZz8fcRP7QII',
    appId: '1:603526614343:web:fc344b521c06fb92c7d062',
    messagingSenderId: '603526614343',
    projectId: 'dukaandiary-ec687',
    authDomain: 'dukaandiary-ec687.firebaseapp.com',
    storageBucket: 'dukaandiary-ec687.firebasestorage.app',
    measurementId: 'G-YR86FN7LYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqmaXNMgfBVz9y8ElWHOK1-ZKGfmYIHRk',
    appId: '1:603526614343:android:d5c8aa49d73fdffec7d062',
    messagingSenderId: '603526614343',
    projectId: 'dukaandiary-ec687',
    storageBucket: 'dukaandiary-ec687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vv8LBAv4Pd8zPJT-G7xS5eUfJpbCeS8',
    appId: '1:603526614343:ios:f0d27e90c50637a1c7d062',
    messagingSenderId: '603526614343',
    projectId: 'dukaandiary-ec687',
    storageBucket: 'dukaandiary-ec687.firebasestorage.app',
    iosBundleId: 'com.example.dukaanDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vv8LBAv4Pd8zPJT-G7xS5eUfJpbCeS8',
    appId: '1:603526614343:ios:f0d27e90c50637a1c7d062',
    messagingSenderId: '603526614343',
    projectId: 'dukaandiary-ec687',
    storageBucket: 'dukaandiary-ec687.firebasestorage.app',
    iosBundleId: 'com.example.dukaanDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK3-ZDjJ5kFiyap-Or-JIzZz8fcRP7QII',
    appId: '1:603526614343:web:40f7aec2953b89b8c7d062',
    messagingSenderId: '603526614343',
    projectId: 'dukaandiary-ec687',
    authDomain: 'dukaandiary-ec687.firebaseapp.com',
    storageBucket: 'dukaandiary-ec687.firebasestorage.app',
    measurementId: 'G-80844ET6T1',
  );
}
